In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import aggrid_weighted_average_sample as m

In [13]:
df = m.build_data()
df

      client  level  volume  price
0   client-B     47    9698    512
1   client-C     68    5580    596
2   client-C     94    6940    295
3   client-B     45    3926    388
4   client-A     87    5039    201
5   client-A     84    8839    981
6   client-A     84    9964    832
7   client-A     45    9050    758
8   client-C     69    3241    171
9   client-C     87    7004    913
10  client-A     36    7802    388
11  client-A     75    3357    679
12  client-C     35    1851    587
13  client-C     93    8116    616
14  client-C     39    7174    656
15  client-C     16    7826    612
16  client-C     60    5377    752
17  client-C     98    8230    392
18  client-C     18    7707    788
19  client-C     15    4683    361

In [34]:
m.build_grid_A(df)

grid saved to plot/plot_grid_A.html
	saved widget div to plot/widget_div_A.html
	saved widget state to plot/widget_state_A.json
open file:
/Users/Olivier/Documents/dev/vue-playground/tiresias/ipyaggrid-weighted-average/plot/plot_grid_A.html

In [35]:
m.build_grid_B(df)

grid saved to plot/plot_grid_B.html
	saved widget div to plot/widget_div_B.html
	saved widget state to plot/widget_state_B.json
open file:
/Users/Olivier/Documents/dev/vue-playground/tiresias/ipyaggrid-weighted-average/plot/plot_grid_B.html